### ISSUE TITLE
mxw.Wallet.createRandom() not working

### ISSUE THREAD

**Issue by bhatti-saqib** [maxonrow/mxw-sdk-js#24]
When I called the mxw.Wallet.createRandom() function, the following error occured.

JS Exception: TypeError: undefined is not an object

I am trying to use this framework in iOS Swift project. And I am using APPLE JavaScriptCore Framework.

**Comment by jeansoonsik** [comment]
Hi. Do you have more details to reproduce it? If you have the sample code is the best!
